<a href="https://colab.research.google.com/github/tiwarisubash956/Machine-Learning-Algorithms/blob/main/pytorch_basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch

In [3]:
print(torch.__version__)

2.11.0+cu128


In [5]:
if torch.cuda.is_available():
  print("GPU is available")
  print(torch.cuda.get_device_name())
else:
  print("GPU not available")

GPU is available
Tesla T4


**Creating tensor**

In [7]:
# creating tensor
# using empty
a=torch.empty(size=(3,3))

In [9]:
# check type
type(a)

torch.Tensor

In [12]:
# using zeros
b=torch.zeros(size=(3,3))
b


tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [13]:
# using one
c=torch.ones(size=(3,3))
c

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [14]:
# using rand
d=torch.rand(size=(3,3))
d

tensor([[0.2674, 0.1351, 0.6433],
        [0.1170, 0.0681, 0.1103],
        [0.7334, 0.8672, 0.8551]])

In [21]:
# use of seed
torch.manual_seed(42)
e=torch.rand(size=(3,3))
e


tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408]])

In [22]:
# using tensor
f=torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
f
#

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [23]:
# other ways
# a range
g=torch.arange(start=0,end=5,step=1)
g

# /line space
h=torch.linspace(start=0.1,end=1,steps=10)
h

# using eye
i=torch.eye(n=3)
i

# using empty_like
j=torch.empty_like(input=i)
j

#full
k=torch.full(size=(3,3),fill_value=7)
k

tensor([[7, 7, 7],
        [7, 7, 7],
        [7, 7, 7]])

**Tensor shape**

In [25]:
x=torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [26]:
x.shape

torch.Size([2, 3])

In [27]:
torch.empty_like(x)

tensor([[   137848600911232,          393381680,       734439407616],
        [318067256258985984,                  0,                  0]])

In [29]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [30]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [39]:
torch.rand_like(x,dtype=float)

tensor([[0.0655, 0.7486, 0.5417],
        [0.4352, 0.5912, 0.0196]], dtype=torch.float64)

**DataType**

In [31]:
x=torch.tensor([[1,2,3],[4,5,6]])


In [32]:
# find data type
x.dtype

torch.int64

In [35]:
# assign data type
torch.tensor([1.9,2.0,3.0,4.0],dtype=int)

tensor([1, 2, 3, 4])

In [37]:
# using to()

x.to(torch.float32)


tensor([[1., 2., 3.],
        [4., 5., 6.]])

**Mathmatical operation on tensor**

1.scalar operation

In [40]:
X=torch.tensor([1,2,3,4])
X

tensor([1, 2, 3, 4])

In [41]:
# addition
X+10

tensor([11, 12, 13, 14])

In [42]:
# subtraction
X-10

tensor([-9, -8, -7, -6])

In [43]:
# multiplication
X*10

tensor([10, 20, 30, 40])

In [44]:
# divsion
X/2

tensor([0.5000, 1.0000, 1.5000, 2.0000])

In [45]:
# int division
(X*100)/3

tensor([ 33.3333,  66.6667, 100.0000, 133.3333])

In [46]:
# mod
((X*100)/3)%2

tensor([1.3333, 0.6667, 0.0000, 1.3333])

In [47]:
# power
X**2

tensor([ 1,  4,  9, 16])

**operation on two or morw than two element**

In [48]:
a=torch.rand(2,3)
b=torch.rand(2,3)

In [49]:
# addition on a and b
a+b


tensor([[0.6407, 0.8441, 0.8378],
        [1.0569, 0.3448, 1.2448]])

In [50]:
# subtraction
a-b

tensor([[ 0.2420, -0.2503,  0.8255],
        [-0.8462,  0.1942, -0.5272]])

In [51]:
# multiplication
a*b

tensor([[0.0880, 0.1625, 0.0051],
        [0.1002, 0.0203, 0.3179]])

In [53]:
# divsion
a/b

tensor([[2.2139e+00, 5.4263e-01, 1.3500e+02],
        [1.1068e-01, 3.5806e+00, 4.0497e-01]])

In [54]:
# abs
torch.abs(a)
#


tensor([[0.4414, 0.2969, 0.8317],
        [0.1053, 0.2695, 0.3588]])

In [55]:
# negative
torch.neg(a)

tensor([[-0.4414, -0.2969, -0.8317],
        [-0.1053, -0.2695, -0.3588]])

In [56]:
# round
torch.round(a)

tensor([[0., 0., 1.],
        [0., 0., 0.]])

In [57]:
# ceil
torch.ceil(a)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [58]:
# floor
torch.floor(a)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [60]:
# clamp
torch.clamp(a,min=2,max=3)

tensor([[2., 2., 2.],
        [2., 2., 2.]])

**Reduction operation**

In [10]:
e=torch.randint(size=(2,3),low=2,high=10,dtype=torch.float)
e

tensor([[8., 2., 3.],
        [7., 8., 6.]])

In [8]:
# sum of elemnents
sum=torch.sum(e)
sum

# sum along rows
sumr=torch.sum(e,dim=1)
sumr

# sum along columns
sumc=torch.sum(e,dim=0)
sumc

tensor([17, 13, 13])

In [12]:
# mean
torch.mean(e)

# mean of colums
torch.mean(e,dim=0)

# mean of rows
torch.mean(e,dim=1)

tensor([4.3333, 7.0000])

In [13]:
# median
torch.median(e)

# median of columns
torch.median(e,dim=0)

# median of rows
torch.median(e,dim=1)

torch.return_types.median(
values=tensor([3., 7.]),
indices=tensor([2, 0]))

In [15]:
# max ,min
print(torch.max(e))
print(torch.min(e))

#

tensor(8.)
tensor(2.)


In [16]:
# product
torch.prod(e)

# product of columns
torch.prod(e,dim=0)

# product of rows
torch.prod(e,dim=1)

tensor([ 48., 336.])

In [17]:
# standard deviation
torch.std(e)

# standard deviation of columns
torch.std(e,dim=0)

# standard deviation of rows
torch.std(e,dim=1)
#

tensor([3.2146, 1.0000])

In [18]:
# varinace
torch.var(e)

# varinace of columns
torch.var(e,dim=0)

# varinace of rows
torch.var(e,dim=1)

tensor([10.3333,  1.0000])

In [20]:
# max along elements using argmax and minimum using arg min
print(torch.argmax(e))
print(torch.argmin(e))

tensor(0)
tensor(1)


**Matrix multiplication**

In [21]:
f=torch.randint(size=(2,3),low=2,high=10,dtype=torch.float)
g=torch.randint(size=(3,2),low=2,high=10,dtype=torch.float)

In [22]:
torch.matmul(f,g)

tensor([[56., 66.],
        [42., 55.]])

In [24]:
# dot product
vector1=torch.tensor([1,3])
vector2=torch.tensor([4,5])
torch.dot(vector1,vector2)

tensor(19)

In [28]:
# tranpose
h=torch.randint(size=(2,2),low=2,high=10,dtype=torch.float)
torch.transpose(h,0,1)

tensor([[9., 2.],
        [9., 3.]])

In [29]:
# determinant
torch.det(h)

tensor(9.)

**Comparision Operation**

In [30]:
i=torch.randint(size=(2,3),low=2,high=10,dtype=torch.float)
j=torch.randint(size=(2,3),low=2,high=10,dtype=torch.float)


In [31]:
# greater than
i>j

tensor([[False,  True,  True],
        [ True, False, False]])

In [32]:
# less than
i <j

tensor([[ True, False, False],
        [False,  True,  True]])

In [33]:
i==j

tensor([[False, False, False],
        [False, False, False]])

In [34]:
i >= j

tensor([[False,  True,  True],
        [ True, False, False]])

**Special Funtion**

In [36]:
# log
torch.log(e)

tensor([[2.0794, 0.6931, 1.0986],
        [1.9459, 2.0794, 1.7918]])

In [37]:
# expontetial
torch.exp(h)

tensor([[8.1031e+03, 8.1031e+03],
        [7.3891e+00, 2.0086e+01]])

In [38]:
# sqrt

torch.sqrt(h)

tensor([[3.0000, 3.0000],
        [1.4142, 1.7321]])

In [39]:
# sigmoid
torch.sigmoid(h)

tensor([[0.9999, 0.9999],
        [0.8808, 0.9526]])

In [41]:
# softmax
torch.softmax(h,dim=0)

tensor([[9.9909e-01, 9.9753e-01],
        [9.1105e-04, 2.4726e-03]])

**inplace Operations**

In [42]:
m=torch.randint(size=(2,3),low=2,high=10,dtype=torch.float)
n=torch.randint(size=(2,3),low=2,high=10,dtype=torch.float)

print(m)
print(n)

tensor([[3., 8., 7.],
        [7., 5., 2.]])
tensor([[5., 6., 5.],
        [5., 6., 8.]])


In [44]:
m.add_(n)
print(m)

tensor([[13., 20., 17.],
        [17., 17., 18.]])


In [46]:
m.relu_()

tensor([[13., 20., 17.],
        [17., 17., 18.]])

**Copying a tensor**

In [48]:
m=n.clone()

In [52]:
m[0][0]=0
n

tensor([[5., 6., 5.],
        [5., 6., 8.]])

**Tensor Operation on GPU**

In [54]:
torch.cuda.is_available()

True

In [56]:
device=torch.device("cuda")

In [57]:
# creating a new tensor on gpu
torch.rand(size=(2,3),device=device)


tensor([[0.1887, 0.7747, 0.9149],
        [0.1141, 0.2509, 0.4128]], device='cuda:0')

In [58]:
# moving old tensor in gpu
m=torch.randint(size=(2,3),low=2,high=10,dtype=torch.float).to(device)


**Reshaping tensor**

In [59]:
a=torch.ones(4,4)

In [60]:
# reshape
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [61]:
# flatten
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [63]:
b=torch.rand(2,3,4)
b

tensor([[[0.3098, 0.8633, 0.4390, 0.9299],
         [0.1083, 0.6036, 0.6331, 0.4791],
         [0.5110, 0.3998, 0.7651, 0.6160]],

        [[0.6853, 0.0228, 0.3945, 0.5458],
         [0.1838, 0.4544, 0.3120, 0.7546],
         [0.3042, 0.1588, 0.3155, 0.2227]]])

In [65]:
# permute
b.permute(2,1,0).shape

torch.Size([4, 3, 2])

In [67]:
# unsqueeze
c=torch.rand(226,226,3)


In [70]:
c.unsqueeze(dim=0).shape

torch.Size([1, 226, 226, 3])

In [71]:
# squeeze
c.squeeze(0).shape

torch.Size([226, 226, 3])

In [73]:
# numpy and pytorch
import numpy as np
c=np.array([1,2,4,5])
torch.from_numpy(c)



tensor([1, 2, 4, 5])